/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercise_lecture;

import com.indvd00m.ascii.render.Render;
import com.indvd00m.ascii.render.api.ICanvas;
import com.indvd00m.ascii.render.api.IContextBuilder;
import com.indvd00m.ascii.render.api.IRender;
import com.indvd00m.ascii.render.elements.PseudoText;
import org.fusesource.jansi.AnsiConsole;
import static org.fusesource.jansi.Ansi.*;
import static org.fusesource.jansi.Ansi.Color.*;



public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        IRender render = new Render();
		IContextBuilder builder = render.newBuilder();
		builder.width(120).height(20);
		builder.element(new PseudoText("DevOps"));
		ICanvas canvas = render.render(builder.build());
		String s = canvas.getText();
        System.out.println(s);

        AnsiConsole.systemInstall();
        System.out.println( ansi().eraseScreen().render("@|red Hello|@ @|green World|@") );
    }
}
